import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";
import { Form1 } from "./form1";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Skar Audio Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav
          className="navbar navbar-light"
          style={{ backgroundColor: "#303846" }}
        >
          <div className="container-fluid">
            <span className="navbar-text text-center">
              <Link href="/">
                <a className="navbar-brand text-white link-light">
                  <Image
                    src="https://core.skaraudio.com/images/skar-audio-logo-white.svg"
                    width="50"
                    height="20"
                  />{" "}
                  Skar Audio Onboarding
                </a>
              </Link>
            </span>
          </div>
        </nav>
      </header>

      <main className="container py-3">
        <Form1 />
      </main>

      <footer className={styles.footer}>Powered by Skar Audio</footer>
    </div>
  );
}
